export { default as Home } from '~/Screen/Home'
export { default as Cart } from '~/Screen/Cart'
export { default as Table } from '~/Screen/Table'
export { default as Checkout } from '~/Screen/Checkout'
export { default as Store } from '~/Screen/Store'